src/main/webapp/PartsOfContent/SiteFooter/FrontFooter.jsp
Footer 내의 Marketing Manager : Jose, Shin 으로 고정 처리
=> Modify Footer Marketing Manager

src/main/java/net/common/Interceptor/StatisticsInterceptor.java, src/main/java/net/mwav/board/controller/BoardController.java, src/main/java/net/mwav/common/module/Common_Utils.java, src/main/java/net/mwav/common/module/StringLib.java, src/main/webapp/PartsOfContent/Head_Import.jsp, src/main/webapp/PartsOfContent/SNS_Head_Import.jsp
Head_Import.jsp - META 쪽 삭제 
SNS_Head_Import.jsp - META 태그 업데이트 
StringLib.java - isEmpty 메소드 업데이트 
BoardController.java - board 내 SEO 키워드 세팅. 
StatisticsInterceptor.java - setMetaData 메소드 내 board meta 데이터 추가.
=> Feature/seo(improvement & framework)dev

src/main/java/net/mwav/common/module/EmailTemplates.java, src/main/java/net/mwav/common/module/ValidationLib.java, src/main/java/net/mwav/member/controller/MemberController.java, src/main/java/net/mwav/member/dao/MemberDAO.java, src/main/java/net/mwav/member/service/MemberServiceImpl.java, src/main/webapp/CommonApps/Member/MbrInput.jsp
1.  EmailTemplates.java : 줄간격 정리, try - catch 제거 및 throws Exception으로 수정(예외처리는 유틸 메서드 단에서 직접 처리하지 않고, 호출부인 비지니스 로직에서 일괄 처리해야함)
2. ValidationLib.java : 영문 주석 작업 및 메서드 수정, Enum 삭제
3. MemberController.java : 줄간격 정리, insertMbrForm() 비지니스 로직 결과에 따른 화면처리 수정
4. MbrInput.jsp : 화면단 유효성 검증 스크립트 수정(정책 미반영 부분 추가) 및 회원가입 form의 auto-complete 기능 없앰(보안문제)
=> Feature/signin ver0.2 bugfix

pom.xml, src/main/java/net/mwav/member/controller/SignController.java, src/main/java/net/mwav/member/service/SignService.java
mwav project 오류 긴급해결
2019.08.05
남동희
1.pom.xml - 에러 hotfix
- mwav-framework maven build는 좀더 검토 필요
2. SignService.java - sns 로그인 관련 mail 발송 및 transaction 처리 추가
=> 2019.08.05

src/main/java/net/mwav/member/service/SignService.java
이메일 sending 오류가 났을 때 프로세스가 on-going 할 수 있도록 예외처리 수정
=> 네이버 sns 로그인 예외처리 수정

src/main/resources/mapper/board/admins/BoardNoticeAdmins_SQL.xml, src/main/resources/mapper/highcharts/HighCharts_SQL.xml, src/main/webapp/Admins/AdminsIndex.jsp, src/main/webapp/Admins/SiteMgr/NewsMgr/NsmFrontList.jsp, src/main/webapp/Admins/SiteMgr/NoticeMgr/NtmFrontList.jsp, src/main/webapp/CommonLibrary/Javascript/custom-chart.js, src/main/webapp/Templates/GeneralMail/GeneralMail_Registration.vm
1. Highchart 출력안되는 내용 수정. 
2. 어드민 페이지 뉴스/공지사항 등 표기 오류 수정. 
3. 회원가입 시 발신되는 이메일 내 회원명 임시 삭제 처리.
=> Feature/admin chart & other error

src/main/webapp/CommonApps/Member/MbrLogin.jsp
단위테스트 및 점검 완료 건. 
1. 네이버 로그인 추가에 따른 우선순위 변경합니다.
=> modify naver login position chagen bottom to Rank 2.

pom.xml, src/main/java/net/mwav/common/module/CompanyInfo.java, src/main/java/net/mwav/common/module/GeneralConfig.java, src/main/java/net/mwav/common/module/TechCompanyInfo.java, src/main/java/net/mwav/common/module/WebSiteInfo.java, src/main/java/net/mwav/common/module/XmlLib.java, src/main/webapp/xConfig/footer.xml, src/test/java/net/mwav/common/module/XmlLibTest.java
XML library 도입
1. xml element object 생성
2. xml library class 생성 및 unmarshal method 추가
3. test case 추가
=> Feature/xml ver0.1

src/test/java/net/mwav/common/module/XmlLibTest.java
=> Feature/xml lib ver0.1

src/main/java/net/mwav/common/module/FileLib.java, src/main/java/net/sample/controller/SampleController.java, src/main/webapp/Admins/Goods/GdsCellForm.jsp, src/main/webapp/CommonApps/Goods/fileUploader.css, src/main/webapp/CommonApps/Goods/fileUploader.js, src/main/webapp/CommonApps/Goods/fileUploader.jsp
작업자 : 정재현, 김주성
FileLib 공통 프론트 파일 개발 (Drag & Drop 기능 포함)
FileLib 작성(업로드, 삭제, 폴더 이동 등)
테스트 방법 :
http://localhost:8080/Admins/Goods/GdsCellForm.mwav?mm=cGds >
어드민 페이지 로그인 : ID : mwavtest / PW : mwav1234!!
상품등록 시 모달 창 내 확인 가능.
단위 테스트 완료 여부 : 완료.
향후 : 경로 지정 등 필요.
=> FileLib 개발

src/main/webapp/CompanyItem/ITProducts/FusionCharts/FusionCharts.jsp, src/main/webapp/CompanyItem/ITProducts/ITProductsLeftMenu.jsp, src/main/webapp/Index.jsp, src/main/webapp/PartsOfContent/SiteHeader/FrontHeader.jsp, src/main/webapp/PartsOfContent/SiteHeader/FrontHeader_Master.jsp
Modify : 
Main > ITSolutions area : Change highchart to fusionchart.
Fixed Fusion Chart layout.
GNB > IT Products : Hyperlink modify QuickHeal to Fusionchart
IT Products > LeftMenu : Give high priority to FusionCharts.
FusionCharts Page : This page renewal the update contents and update new parter-media-kit received from fusion charts
=> UI_FusionChart layout

src/main/java/net/mwav/common/module/MathLib.java
- MathLib.getRandomInt() 개발 완료
- 간략한 주석 정리
=> MathLib.getRandomInt() 개발

src/main/java/net/mwav/common/module/SecurityLib.java, src/test/java/net/mwav/common/module/SecurityLibTest.java
- SecurityLib 개발
: aes 128 암호화, 복호화 기능 개발(진행 중)
=> SecurityLib 개발

pom.xml
빌드 에러에 따른 수정 건.
1) Pom.xml 내 기본 디폴티 maven repositiry 삭제
2) Azrue remote reposition 명명 수정.
=> Error update pom.xml

src/main/java/net/common/filter/HttpsFilter.java, src/main/resources/config/spring/mwav-data.xml
=> Feature/set up the stg,dev environment

src/main/java/net/common/common/Status.java
=> no message

.github/auto_assign.yml
=> ADD autoassign

src/main/java/net/common/filter/HttpsFilter.java, src/main/webapp/CommonApps/BoardNews/bnsView.jsp, src/main/webapp/CommonApps/BoardNotice/buView.jsp, src/main/webapp/CustomerService/SiteMap/SiteMap.txt, src/main/webapp/CustomerService/SiteMap/SiteMap.xml, src/main/webapp/PartsOfContent/SNS_Head_Import.jsp, src/main/webapp/Templates/GeneralMail/GeneralMail_Registration.vm, src/main/webapp/Templates/GeneralMail/PWSeekEmail.html, src/main/webapp/Templates/QnAnswer/QuestionAnswer.html, src/main/webapp/Templates/QnAnswer/QuestionAnswer.vm, src/main/webapp/resources/CommonLibrary/CSS/mwav_style.css
-java source rollback request because of the completion of SSL expire date.
-Change to http> https after source transfer.
=> Hotfix-00001

pom.xml
pom.xml 에서 prd profile 부분 작업 추가
배포시, production용 application.properties 설정 파일을 적용하기 위함
=> [Devops] Update pom.xml

src/main/java/net/admins/service/GoodsAdminsFileHandler.java
Develop 소스에 오류가 있어서 수정.
변수선언이 되지 않음.
변수 선언 완료.
=> Hotfix-00003

src/main/java/net/bizLogin/promoter/controller/PmtFacilitatorController.java, src/main/java/net/bizLogin/promoter/dao/PmtFacilitatorDAO.java, src/main/java/net/bizLogin/promoter/service/PmtFacilitatorService.java, src/main/java/net/bizLogin/promoter/service/PmtFacilitatorServiceImpl.java, src/main/java/net/bizLogin/promoter/vo/PmtFacilitatorPO.java, src/main/java/net/bizLogin/promoter/vo/PmtFacilitatorSO.java, src/main/java/net/bizLogin/promoter/vo/PmtFacilitatorVO.java, src/main/resources/mapper/promoter/Promoter_SQL.xml, src/main/webapp/Promoter/Facilitator/PmtLogin.jsp, src/main/webapp/Promoter/PartsOfContent/SiteHeader/PmtSiteHeader.jsp
=> BizLogin-0004

src/main/java/net/mwav/member/dao/MemberDAO.java, src/main/java/net/mwav/member/service/MemberServiceImpl.java, src/main/resources/mapper/member/Member_SQL.xml, src/main/webapp/CommonApps/Member/MbrLogin.jsp
대부분의 테이블 및 컬럼 변경으로 오류사항 수정 조치 작업
정상적으로 서비스를 실행하기 위함
추가된 테이블이나 컬럼에 대해서 하드코딩으로 데이터를 넣었음
추가개발이 필요할 듯 함
추가예정
=> Bizlogin-00013

.github/CODEOWNERS
=> [UPT] CODEOWNERS List

src/main/webapp/CompanyItem/ITProducts/OfficeSuite/OfficeSuite.jsp
Footer 내 link가 오기입되어서 해당 내용 수정.
=> UPT OfficeSuite footer page change include link

src/main/java/net/admins/controller/CommonController.java, src/main/webapp/CompanyItem/ITProducts/OfficeSuite/OfficeSuite.jsp
=> BizLogin-00018

src/main/webapp/ChatBot_dev.html
- 챗봇 고도화.
- 챗봇 테스트 Dev 환경 구성.
- 운영 URL에서 챗봇 테스트 진행 실시 가능. 
- URL 및 경로는 추후 변경 예정.
=> BizLogin-00012

src/main/webapp/CommonApps/Member/MbrLogin.jsp
- 소셜 로그인 에러 케이스에 대해서 임시 삭제
- 작동하지 않는 기능을 노출 함으로써 사이트 신뢰 삭제
- 임시로 대상 페이지를 삭제한다.
=> Update Social login page error

src/main/java/net/bizLogin/promoter/controller/PmtFacilitatorController.java, src/main/java/net/bizLogin/promoter/dao/PmtFacilitatorDAO.java, src/main/java/net/bizLogin/promoter/service/PmtFacilitatorService.java, src/main/java/net/bizLogin/promoter/service/PmtFacilitatorServiceImpl.java, src/main/java/net/bizLogin/promoter/vo/BizPromoter_VO.java, src/main/resources/mapper/promoter/Promoter_SQL.xml, src/main/webapp/Promoter/Facilitator/PmtCertifyPage.jsp, src/main/webapp/Promoter/Facilitator/PmtLogin.jsp, src/main/webapp/Promoter/PartsOfContent/SiteHeader/PmtSiteHeader.jsp, src/test/java/net/bizLogin/promoter/controller/PmtFacilitatorControllerTest.java, src/test/java/net/bizLogin/promoter/dao/PmtFacilitatorDAOTest.java
=> BizLogin-00011

src/main/webapp/Promoter/Facilitator/PmtUpdateForm.jsp, src/main/webapp/Promoter/Facilitator/PmtView.jsp
=> BizLogin-00023

pom.xml, src/main/java/net/admins/vo/Staff_VO.java, src/main/java/net/common/Interceptor/AuthInterceptor.java, src/main/java/net/common/Interceptor/StatisticsInterceptor.java, src/main/java/net/common/common/FrontCommonController.java, src/main/java/net/common/filter/HTMLTagFilter.java, src/main/java/net/common/filter/HttpsFilter.java, src/main/java/net/common/resolver/CustomMapArgumentResolver.java, src/main/java/net/mwav/board/controller/BoardController.java, src/main/java/net/mwav/common/module/Common_Utils.java, src/main/java/net/mwav/member/auth/naver/NaverUrlBuilder.java, src/main/java/net/mwav/member/vo/Member_tbl_VO.java, src/main/resources/config/spring/mwav-data.xml, src/main/resources/log4j.xml
Revise logger
- delete spring boot dependency
- delete unnecessary log.info
=> [hotfix-00007]

src/main/java/net/newmember/controller/NewMemberController.java
=> 템플릿 오타 오류 수정

src/main/java/net/newmember/controller/NewMemberController.java, src/main/webapp/Templates/GeneralMail/NewMemberAlarmEmail.vm, src/main/webapp/Templates/GeneralMail/NewMemberSendEmail.html
=> 템플릿 수정 및 메일제목변경
